EVAL_CROP_SIZE: (2048, 1024) # (width, height), for unpadding rangescaling and stepscaling
TRAIN_CROP_SIZE: (1024, 512) # (width, height), for unpadding rangescaling and stepscaling

AUG:
#    AUG_METHOD: "unpadding" # choice unpadding rangescaling and stepscaling
    AUG_METHOD: "stepscaling" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (1024, 512) # (width, height), for unpadding
    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.5  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    MIRROR: True

    RICH_CROP.ENABLE: True
    RICH_CROP.BLUR: True
    RICH_CROP.BLUR_RATIO: 0.2
    RICH_CROP.BRIGHTNESS_JITTER_RATIO: 0.2
    RICH_CROP.SATURATION_JITTER_RATIO: 0.2
    RICH_CROP.CONTRAST_JITTER_RATIO: 0.2

BATCH_SIZE: 4
# BATCH_SIZE: 4

DATASET:
    DATA_DIR: "/mnt/data/zyh/datasets/data/"
    NUM_CLASSES: 20
    TEST_FILE_LIST: "/mnt/data/zyh/datasets/data/test_list_baseline.txt"
    TRAIN_FILE_LIST: "/mnt/data/zyh/datasets/data/train_list_baseline.txt"
    VAL_FILE_LIST: "/mnt/data/zyh/datasets/data/val_list_baseline.txt"
    VIS_FILE_LIST: "/mnt/data/zyh/datasets/data/test_list_baseline.txt"
FREEZE:
    MODEL_FILENAME: "model"
    PARAMS_FILENAME: "params"

MODEL:
    MODEL_NAME: "ocrnet"
    DEFAULT_NORM_TYPE: "bn"
    HRNET:
        STAGE2:
            NUM_CHANNELS: [18, 36]
        STAGE3:
            NUM_CHANNELS: [18, 36, 72]
        STAGE4:
            NUM_CHANNELS: [18, 36, 72, 144]
    OCR:
        OCR_MID_CHANNELS: 512
        OCR_KEY_CHANNELS: 256
    MULTI_LOSS_WEIGHT: [1.0, 1.0]
TRAIN:
    PRETRAINED_MODEL_DIR: u"./pretrained_model/ocrnet_w18_cityscape/best_model"
    MODEL_SAVE_DIR: "output/ocrnet_w18_bn_cityscapes"
    SNAPSHOT_EPOCH: 1
    SYNC_BATCH_NORM: True
TEST:
    TEST_MODEL: "output/ocrnet_w18_bn_cityscapes/first"
SOLVER:
    LR: 0.01
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"
    NUM_EPOCHS: 500
    LOSS: ["lovasz_softmax_loss","softmax_loss"]
    LOSS_WEIGHT:
        LOVASZ_SOFTMAX_LOSS: 0.2
        SOFTMAX_LOSS: 0.8