# 数据集配置
DATASET:
    DATA_DIR: "/home/zxl/hualu-laneline-detection/data/"
    NUM_CLASSES: 20
    TRAIN_FILE_LIST: "/home/zxl/hualu-laneline-detection/data/train_list.txt"
    VAL_FILE_LIST: "/home/zxl/hualu-laneline-detection/data/val_list.txt"
    TEST_FILE_LIST: "/home/zxl/hualu-laneline-detection/data/test_list.txt"
    VIS_FILE_LIST: "/home/zxl/hualu-laneline-detection/data/test_list.txt"

# 预训练模型配置
MODEL:
    MODEL_NAME: "hrnet"
    DEFAULT_NORM_TYPE: "bn"
    HRNET:
        STAGE2:
            NUM_CHANNELS: [48, 96]
        STAGE3:
            NUM_CHANNELS: [48, 96, 192]
        STAGE4:
            NUM_CHANNELS: [48, 96, 192, 384]

# 其他配置
MEAN: [0.469, 0.504, 0.497]
STD: [0.248, 0.255, 0.275]

TRAIN_CROP_SIZE: (512, 512)
EVAL_CROP_SIZE: (910, 512)

AUG:
    AUG_METHOD: "unpadding"
    FIX_RESIZE_SIZE: (910, 512)

    MIRROR: True

    RICH_CROP.ENABLE: True
    RICH_CROP.MIN_AREA_RATIO: 0.6
    RICH_CROP.ASPECT_RATIO: 0.6

#    RICH_CROP.ENABLE: True
#    RICH_CROP.BLUR: True
#    RICH_CROP.BLUR_RATIO: 0.2
#    RICH_CROP.BRIGHTNESS_JITTER_RATIO: 0.2
#    RICH_CROP.SATURATION_JITTER_RATIO: 0.2
#    RICH_CROP.CONTRAST_JITTER_RATIO: 0.2

BATCH_SIZE: 12
TRAIN:
    PRETRAINED_MODEL_DIR: "./pretrained_model/hrnet_w48_bn_imagenet/"
    MODEL_SAVE_DIR: "./saved_model/hr48-weight-2/"
    SYNC_BATCH_NORM: True
    SNAPSHOT_EPOCH: 4
TEST:
    TEST_MODEL: "./saved_model/hr48-weight-2/best_model"
SOLVER:
    NUM_EPOCHS: 60
    LR: 0.00001
    LR_POLICY: "cosine"
    CROSS_ENTROPY_WEIGHT: [1.43316, 10.63711, 27.34519, 9.94707, 26.16396, 32.04059, 30.50304, 27.03949, 20.15837, 19.65944, 25.59547, 42.39117, 34.16391, 29.56095, 34.82022, 39.46073, 42.90119, 44.11740, 44.11740, 12.81496],
    OPTIMIZER: "adam"
    LOSS: ["softmax_loss"]
    LOSS_WEIGHT:
        SOFTMAX_LOSS: 1
