# 数据集配置
DATASET:
    DATA_DIR: "/home/zxl/hualu-laneline-detection/data/"
    NUM_CLASSES: 20
    TRAIN_FILE_LIST: "/home/zxl/hualu-laneline-detection/data/train_list.txt"
    VAL_FILE_LIST: "/home/zxl/hualu-laneline-detection/data/val_list.txt"
    TEST_FILE_LIST: "/home/zxl/hualu-laneline-detection/data/test_list.txt"
    VIS_FILE_LIST: "/home/zxl/hualu-laneline-detection/data/test_list.txt"

# 预训练模型配置
MODEL:
    MODEL_NAME: "mt-hrnet"
    DEFAULT_NORM_TYPE: "bn"
    HRNET:
        STAGE2:
            NUM_CHANNELS: [18, 36]
        STAGE3:
            NUM_CHANNELS: [18, 36, 72]
        STAGE4:
            NUM_CHANNELS: [18, 36, 72, 144]

# 其他配置
TRAIN_CROP_SIZE: (256, 256)
EVAL_CROP_SIZE: (256, 256)
AUG:
    AUG_METHOD: "unpadding"
    FIX_RESIZE_SIZE: (256, 256)

    MIRROR: True

    RICH_CROP.ENABLE: True
    RICH_CROP.BLUR: True
    RICH_CROP.BLUR_RATIO: 0.2
    RICH_CROP.BRIGHTNESS_JITTER_RATIO: 0.2
    RICH_CROP.SATURATION_JITTER_RATIO: 0.2
    RICH_CROP.CONTRAST_JITTER_RATIO: 0.2

    # TRAIN_CROP_SIZE: (512, 512)
    # EVAL_CROP_SIZE: (512, 512)

BATCH_SIZE: 3
TRAIN:
    PRETRAINED_MODEL_DIR: "./pretrained_model/hrnet_w18_bn_cityscapes/"
    MODEL_SAVE_DIR: "./saved_model/3738-hr18-base/"
    SNAPSHOT_EPOCH: 3
TEST:
    TEST_MODEL: "./saved_model/3738-hr18-base/best_model"
SOLVER:
    NUM_EPOCHS: 40
    LR: 0.0003
    LR_POLICY: "poly"
    OPTIMIZER: "adam"
#    LOSS: ["lovasz_softmax_loss","softmax_loss"]
    LOSS: ["softmax_loss", "lane_width_loss"]
    LOSS_WEIGHT:
#        LOVASZ_SOFTMAX_LOSS: 0.8
#        SOFTMAX_LOSS: 0.8
        LANE_WIDTH_LOSS: 1
